CREATE OR REPLACE FUNCTION set_updated_at_ts()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    return NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE documents (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pub_id UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    title text,
    contents JSONB NOT NULL
);

CREATE TRIGGER set_documents_updated_at
BEFORE UPDATE ON documents
FOR EACH ROW
EXECUTE PROCEDURE set_updated_at_ts();
